---
# =============================================================================
# Official documentation: https://terraform-docs.io/user-guide/configuration
# =============================================================================

# The default name of the configuration file is .terraform-docs.yml. The path order for locating it is:

#     root of module directory
#     .config/ folder at root of module directory
#     current directory
#     .config/ folder at current directory
#     $HOME/.tfdocs.d/

# if .terraform-docs.yml is found in any of the folders above, that will take precedence and will override the other ones.

# =============================================================================

# Only required field
formatter: "markdown document"

version: ">= 0.18.0, < 1.0.0"

sections:
  show: ["all"]

content: |-

  ## Usage

  You can use this module as a `terragrunt` unit as follows:

  ```hcl
  terraform {
    source = "git::git@github.com:ajcandfield/my-tf-modules.git//modules/...?ref=vX.X.X"
  }

  include "root" { path = find_in_parent_folders() }

  dependency "" { config_path = "" }

  locals {}

  inputs = {
  {{- if .Module.RequiredInputs }}
    # Required variables
    {{- range .Module.RequiredInputs }}
    {{ .Name | printf "%-25s" }} = "{{ .GetValue }}"
    {{- end }}
  {{- end }}{{"\n"}}

  {{- if .Module.OptionalInputs }}
    # Optional variables
    {{- range .Module.OptionalInputs }}
    {{ .Name | printf "%-25s" }} = {{ .GetValue | printf "%s" }}
    {{- end }}
  {{- end }}
  }
  ```

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Modules }}

  {{ .Resources }}

output:
  file: "README.md"
  mode: inject

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
